apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-pv-claim
  labels:
    app: myapp
spec:
  storageClassName: ocs-storagecluster-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-busybox
  labels:
    app: myapp
    tier: busybox
spec:
  selector:
    matchLabels:
      app: myapp
      tier: busybox
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myapp
        tier: busybox
    spec:
      containers:
      - image: busybox
        name: busybox
        command: ['sh', '-c', 'echo The app is running! && sleep 3600']
        volumeMounts:
        - name: busybox-persistent-storage
          mountPath: /var/lib/busybox
      volumes:
      - name: busybox-persistent-storage
        persistentVolumeClaim:
          claimName: busybox-pv-claim

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1-busybox
  labels:
    app: myapp1
    tier: busybox
spec:
  selector:
    matchLabels:
      app: myapp1
      tier: busybox
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myapp1
        tier: busybox
    spec:
      containers:
      - image: busybox
        name: busybox
        command: ['sh', '-c', 'echo The app is running! && sleep 3600']
        volumeMounts:
        - name: busybox-persistent-storage
          mountPath: /var/lib/busybox
      volumes:
      - name: busybox-persistent-storage
        persistentVolumeClaim:
          claimName: busybox-pv-claim


