apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raw-pv-claim
spec:
  storageClassName: TODO
  accessModes:
  - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
